//
//  MPArgumentProcessor.m
//  MacDown
//
//  Created by Tzu-ping Chung on 02/12.
//  Copyright (c) 2014 Tzu-ping Chung . All rights reserved.
//

#import "MPArgumentProcessor.h"
#import <GBCli/GBCli.h>
#import "MPGlobals.h"


@interface MPArgumentProcessor ()

@property (strong) GBCommandLineParser *parser;
@property (strong) GBOptionsHelper *options;
@property (strong) GBSettings *settings;

@end


/** A value from the Info.plist of the application this utility lives in.
 *
 * It reported 0.9.1 for nine releases. The number came from a generated
 * header, the generator was never run by the build, and so the file that
 * was committed years ago was the answer — a version that has to be
 * regenerated by hand is a version that will be wrong.
 *
 * The utility is installed at `App.app/Contents/SharedSupport/bin/`, so the
 * bundle it belongs to is three directories above its own. Read from there
 * it cannot drift from what the application itself reports, whatever the
 * build did or did not do.
 */
static NSString *MPVersionFromContainingApp(NSString *key,
                                            const char *fallback)
{
    NSString *here = [NSBundle mainBundle].bundlePath;
    NSString *app = here.stringByDeletingLastPathComponent
        .stringByDeletingLastPathComponent.stringByDeletingLastPathComponent;

    NSBundle *bundle = [app.pathExtension isEqualToString:@"app"]
        ? [NSBundle bundleWithPath:app] : nil;
    NSString *value = bundle.infoDictionary[key];
    if (value.length)
        return value;
    return [NSString stringWithUTF8String:fallback];
}

@implementation MPArgumentProcessor

- (instancetype)init
{
    self = [super init];
    if (!self)
        return nil;

    // Init options.
    GBOptionsHelper *options = [[GBOptionsHelper alloc] init];
    options.applicationVersion = ^{
        return MPVersionFromContainingApp(@"CFBundleShortVersionString",
                                         kMPApplicationShortVersion);
    };
    options.applicationBuild = ^{
        return MPVersionFromContainingApp(@"CFBundleVersion",
                                          kMPApplicationBundleVersion);
    };
    options.applicationName = ^{ return kMPApplicationName; };
    options.printHelpHeader = ^{
        NSString *fmt =
            @"usage: %@ [file ...]\n\nOptions:";
        return [NSString stringWithFormat:fmt, kMPCommandName];
    };
    [options registerOption:'v' long:kMPVersionKey
                description:@"Print the version and exit."
                      flags:GBOptionNoValue];
    [options registerOption:'h' long:kMPHelpKey
                description:@"Print this help message and exit."
                      flags:GBOptionNoValue];
    self.options = options;

    self.settings = [[GBSettings alloc] initWithName:@"command-line"
                                              parent:nil];

    // Create parser and parse.
    GBCommandLineParser *parser = [[GBCommandLineParser alloc] init];
    [parser registerSettings:self.settings];
    [parser registerOptions:self.options];
    self.parser = parser;

    [self.parser parseOptionsUsingDefaultArguments];

    return self;
}

- (BOOL)printsHelp
{
    return [self.settings boolForKey:kMPHelpKey];
}

- (BOOL)printsVersion
{
    return [self.settings boolForKey:kMPVersionKey];
}

- (NSArray *)arguments
{
    return self.parser.arguments;
}

- (void)printHelp:(BOOL)shouldExit
{
    [self.options printHelp];
    if (shouldExit)
        exit(EXIT_SUCCESS);
}

- (void)printVersion:(BOOL)shouldExit
{
    [self.options printVersion];
    if (shouldExit)
        exit(EXIT_SUCCESS);
}

@end
